### ISSUE TITLE
Instalacion

### ISSUE THREAD

**Issue by maxsegur** [gepd/HTTP-DTE#3]
Estimado, primera vez que trabajo con Docker y me cuesta un poco. Podrías.documentar la instalación y ejemplos.de.uso por favor. Llegué a localhost:3001 y me da el.error de la firma. Y después de eso?
Es necesario el entorno gráfico para slim? 
Uso debían 10 sin entorno gráfico, php7.4, apache2, slim4, todo en una máquina virtual. Necesito algo de ayuda para saber cómo funciona. Saludos

**Comment by gepd** [comment]
Una vez que ya tienes los contenedores corriendo, debes enviar una petición POST al servidor que está en el puerto 8000

El ejemplo de PHP muestra:

```php
$url = 'http://dte-api:8000/dte/estado';
$ch = curl_init($url);

curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");                                                                     
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

$server_output = curl_exec ($ch);
```

como puedes ver en la url se está solicitando el estado de un documento `http://dte-api:8000/dte/estado` (puedes ver la lista completa de peticiones [aqui](https://github.com/gepd/HTTP-DTE/blob/develop/ENDPOINTS.md))

Para codificar tu certificado en base64 tienes que hacer algo así

```php
$filename = "certificado.pfx";
$cert = file_get_contents($filename);
$file64 = base64_encode($cert);
```
el valor de `$file64` es tu firma en base64

Para solicitar el estado de un documento necesitas enviar en el cuerpo (body) de la petición lo siguiente:

```json
{
  "rut": "",
  "trackId": "",
  "Firma": {
    "data": "", // Firma codificada en base64
    "pass": ""
  }
}
```
```php
// variable para enviar en body
$data = array('rut' => '12345678-9', 'trackId' => '34112441', 'firma' => array('data': $file64, 'pass': '1234');
```
`$data` es el valor que vas a enviar a tu API, ahora el servidor ya debería estar retornando alguna respuesta.

Si quieres probar la API sin necesidad de php, puedes hacerlo usando algún cliente como postman, puedes ejecutar `docker-compose up -f ./docker-compose.api.yml` y hacer lo mismo que te expliqué anteriormente desde allí apuntando a la url `http://localhost:8000`

**Comment by gepd** [comment]
cerrado por inactividad
